
import { Timestamp } from 'firebase/firestore'

/**
 * Location object for 3x2 freezer track system
 */
export interface Location {
  track: number           // 1, 2, or 3 (row)
  position: number        // 1 or 2 (column)
  label: string          // "T1-P1" (formatted)
  description: string    // "Track 1, Position 1"
  movedAt?: Timestamp    // When item was last moved
  movedBy?: string       // User UID who moved item
}

/**
 * Represents an inventory item in the Freezer database (FINAL SCHEMA)
 */
export interface InventoryItem {
  // ========== IDENTIFIERS ==========
  id: string                           // Auto-generated by Firestore

  // ========== CORE INFORMATION (REQUIRED) ==========
  name: string                         // Item name (e.g., "Sodium Chloride Solution")
  company: string                      // Manufacturer/supplier (e.g., "Sigma-Aldrich")
  volume: string                       // Volume/quantity (e.g., "100ml", "50g", "1L")
  quantity: number                     // Stock quantity (default: 1)
  
  // ========== OPTIONAL DETAILS ==========
  concentration?: string               // e.g., "0.5M", "95%", "pH 7.4"
  
  // ========== CATEGORIZATION ==========
  category: '4C' | '-20C'              // Temperature zone (REQUIRED)
  // 4C = Refrigerator (2-8°C)
  // -20C = Freezer (-16 to -24°C)
  
  // ========== IDENTIFICATION & TRACKING ==========
  barcode: string                      // e.g., "123456789" (REQUIRED)
  qrCode: string                       // e.g., "QR-12345" (REQUIRED)
  batchNumber?: string                 // e.g., "LOT-20240115"
  serialNumber?: string                // e.g., "SN-ABC123"
  casNumber?: string                   // e.g., "7732-18-5" (CAS number for chemicals)
  
  // ========== LOCATION TRACKING ==========
  location: Location                   // 3x2 track storage system
  locationLabel: string                // "T1-P1" (denormalized for fast queries)
  
  // ========== DATES ==========
  purchaseDate: Timestamp | null       // When purchased
  expirationDate: Timestamp | null     // When expires
  
  // ========== STATUS & LIFECYCLE ==========
  status: 'active' | 'expired' | 'archived' | 'removed'
  // active: In use, not expired
  // expired: Past expiration date
  // archived: No longer in active use
  // removed: Deleted by user/admin
  
  // ========== CHECKOUT TRACKING ==========
  borrowedBy?: string                  // User UID who borrowed it
  borrowedAt?: Timestamp               // When borrowed
  expectedReturnDate?: Timestamp       // Expected return date
  
  // ========== METADATA ==========
  notes: string                        // Additional notes (default: "")
  createdAt: Timestamp                 // Auto-set on creation (server time)
  createdBy: string                    // User role/UID who created it
  updatedAt: Timestamp                 // Auto-set on updates (server time)
  updatedBy?: string                   // Last user to modify
}

/**
 * Edit history entry for user-created items
 */
export interface EditHistoryEntry {
  id: string                           // Auto-generated
  itemId: string                       // Reference to parent item
  
  // ========== CHANGE INFORMATION ==========
  action: 'create' | 'update' | 'delete'
  changedBy: string                    // User UID or role
  changedAt: Timestamp                 // Server timestamp
  
  // ========== CHANGE DETAILS ==========
  changes: {
    [fieldName: string]: {
      before: unknown                      // Previous value
      after: unknown                       // New value
    }
  }
  
  // ========== CONTEXT ==========
  reason?: string                      // Why the change was made
  notes?: string                       // Additional context
}

/**
 * Checkout record for item borrowing
 */
export interface Checkout {
  id: string                           // Auto-generated
  
  // ========== ITEM & USER ==========
  inventoryId: string                  // Reference to Inventory/{id}
  userId: string                       // User who borrowed
  
  // ========== CHECKOUT DETAILS ==========
  checkedOutAt: Timestamp              // When borrowed
  quantity: number                     // How many units borrowed
  expectedReturnDate: Timestamp        // When should be returned
  actualReturnDate?: Timestamp         // When actually returned
  
  // ========== STATUS ==========
  status: 'active' | 'returned' | 'overdue' | 'lost'
  
  // ========== TRACKING ==========
  purpose?: string                     // Why borrowed
  location?: string                    // Where taken
  notes?: string                       // Additional notes
}

/**
 * User profile with role and permissions
 */
export interface User {
  id: string                           // Firebase UID
  email: string
  displayName: string
  role: 'student' | 'admin' | 'superadmin'
  createdAt: Timestamp
  lastLogin: Timestamp
  lastActivity: Timestamp
  status: 'active' | 'inactive' | 'suspended'
  loginCount: number
  itemsCreated: number
}

/**
 * Admin audit log entry
 */
export interface AuditLogEntry {
  id: string                           // Auto-generated
  
  // ========== ACTION INFO ==========
  action: 'create' | 'update' | 'delete' | 'checkout' | 'return' | 'user_manage'
  admin: string                        // Admin UID
  performedAt: Timestamp               // Server timestamp
  
  // ========== TARGETS ==========
  targetType: 'inventory' | 'user' | 'checkout'
  targetId: string                     // ID of item/user/checkout
  
  // ========== DETAILS ==========
  changes?: {
    [fieldName: string]: {
      before: unknown
      after: unknown
    }
  }
  
  // ========== METADATA ==========
  ipAddress?: string
  userAgent?: string
  reason?: string
  notes?: string
}

/**
 * Location metadata (for separate Locations collection)
 */
export interface LocationMetadata {
  id: string                           // "T1-P1"
  track: number                        // 1, 2, or 3
  position: number                     // 1 or 2
  label: string                        // "T1-P1"
  description: string                  // "Track 1, Position 1 (Top-Left)"
  capacity: number                     // Max items
  currentCount: number                 // Current items
  temperatureZone: '4C' | '-20C'       // Which freezer
  notes?: string
  lastAuditedAt?: Timestamp
  isActive: boolean
}

/**
 * Form data for adding new inventory items
 */
export interface NewInventoryItemInput {
  name: string
  company: string
  volume: string
  quantity: number
  concentration?: string
  purchaseDate: string
  expirationDate: string
  notes: string
  batchNumber?: string
  serialNumber?: string
  casNumber?: string
  location?: {
    track: number
    position: number
  }
  category: '4C' | '-20C'
  barcode: string
  qrCode: string
}

/**
 * API response for list endpoints
 */
export interface ApiListResponse<T> {
  success: boolean
  data: T[]
  total?: number
  message?: string
}

/**
 * API response for single item endpoints
 */
export interface ApiItemResponse<T> {
  success: boolean
  data: T
  message?: string
}

/**
 * Cart item with quantity
 */
export interface CartItem extends InventoryItem {
  cartQuantity?: number  // Quantity in cart (separate from inventory quantity)
}
